function createfigure(X1, YMatrix1, YMatrix2, YMatrix3)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2, YMATRIX3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 10-Aug-2015 11:05:27

% Create figure
figure1 = figure('NumberTitle','off');

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineStyle','--');
set(plot1(1),'Color',[1 0 0]);
set(plot1(2),'Color',[0 0 1]);

% Create ylabel
ylabel({'Y[0]'});

% Create xlabel
xlabel({''});

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineStyle','--');
set(plot2(1),'Color',[1 0 0]);
set(plot2(2),'Color',[0 0 1]);

% Create ylabel
ylabel({'Y[1]'});

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
box(subplot3,'on');
hold(subplot3,'all');

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',subplot3,'LineStyle','--');
set(plot3(1),'Color',[1 0 0],'DisplayName','Label');
set(plot3(2),'Color',[0 0 1],'DisplayName','Network Prediction');

% Create ylabel
ylabel({'Y[2]'});

% Create xlabel
xlabel({'Frame Number'});

% Create legend
legend1 = legend(subplot3,'show');
set(legend1,...
    'Position',[0.783855716765866 0.0156312670099353 0.124674479166667 0.0530217717717718]);

